typography_spectrum: 0.86996
color:
  brandColors:
    - '#ffffff'
    - '#003677'
    - '#72ce38'
    - '#b8e69a'
    - '#6c99b9'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34007
analytics:
  google: null
  facebook: null
  twitter: null
name: cplatforms
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: CardPlatforms
purpose: []
